### ISSUE TITLE
oktw aio

### ISSUE THREAD

**Issue by ghost** [Decaed/BloodMoon#1]
oktw aio has an anivia script is there any chance u could update it so it's compatible with ensoulsharp?

**Comment by ghost** [comment]
https://github.com/OneKeyToWin/OKTW2/blob/main/OneKeyToWin_AIO_Sebby/OneKeyToWin_AIO_Sebby/Champions/Anivia.cs

also this is the link to the script. idk if it's possible to make it work with ensoul but i'd really appreciate it if u could

**Comment by Decaed** [comment]
It requires a complete rewrite.

**Comment by Decaed** [comment]
It requires a complete rewrite. I have looked at the code for another issue, but it will require too much work and I don't have the time. I have now removed it from my repository. Sorry.
